### ISSUE TITLE
--multiple?

### ISSUE THREAD

**Issue by AcarBurak** [Israel-/zlocate#1]
Many thanks for this fine utility. I've added "--multiple" to the line 55, but only the first item is activated. Any guidance?

**Comment by Israel-** [comment]
Hi @AcarBurak 
zenity outputs a list separated by my defined | separator
So your list will be returned as:
item1|item2|item3

line 60 & 61
```
RESULT=$(echo ${RESULT}| cut -d'|' -f1)
[[ -n "${RESULT}" ]] && xdg-open "${RESULT}"
```
The line
RESULT=$(echo ${RESULT}| **cut -d'|' -f1**)
cuts everything after the first field

Would need to become an array
So something like this might work
```
   OIFS=$IFS
   IFS="|"
   RESULT=(echo ${RESULT})
  
   for x in "${RESULT[@]}
   do
     xdg-open "$x"
   done
   IFS=$OIFS
```

**Comment by AcarBurak** [comment]
I'd tried to remove that cut... parts, without success! Thank you.

**Comment by Israel-** [comment]
@AcarBurak did this work for you?  If so I'll close this issue.

**Comment by AcarBurak** [comment]
Embarrased to ask for more detail! No I couldn't work it out. Don't know where to put it. I've tried replacing 57-62 with the above but it didn't work.

**Comment by Israel-** [comment]
Hi I just added a commit with the ability to add a command line argument to make it multiple
currently ANY extra parameter will cause it to use multiple lines.
so get the latest version and test it
./zlocate <anything_extra>
i.e
./zlocate -m
If this works I will make it a bit nicer and set a multiple argument for the program

**Comment by AcarBurak** [comment]
Thanks a lot. Yes, it works now.

**Comment by Israel-** [comment]
OK @AcarBurak this should fix it... I also changed it so now you need
`-m`
OR
`--multiple`
for it to work with multiple files

**Comment by AcarBurak** [comment]
Thank you.
